apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: yu-test-nim-deployment-1
  namespace: yu-nim-test-project-1
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: yu-test-nim-deployment-1
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
spec:
  predictor:
    minReplicas: 3
    maxReplicas: 3
    model:
      modelFormat:
        name: mistral-7b-instruct-v03
      runtime: yu-test-nim-deployment-1
      storage:
        key: ''
        path: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: 2
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: 2
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: odh-notebook
        operator: Exists
