apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: yu-test-nim-deployment-4
  namespace: yu-nim-test-project-4
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: yu-test-nim-deployment-4
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
spec:
  predictor:
    minReplicas: 2
    maxReplicas: 2
    model:
      modelFormat:
        name: mixtral-8x22b-instruct-v01
      runtime: yu-test-nim-deployment-4
      storage:
        key: ''
        path: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: 1
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: 1
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: odh-notebook
        operator: Exists