apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  name: nvidia-runtime-gpu
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: NVIDIA Inference Microservice
spec:
  supportedModelFormats: []
  protocolVersions:
    - grpc-v2
  multiModel: false
  containers:
    - env:
        - name: NIM_CACHE_PATH
          value: /mnt/models
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: nvidia-nim-secrets
      name: kserve-container
      image: null
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: 2
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: 2
      ports:
        - containerPort: 8000
          protocol: TCP
  imagePullSecrets:
    - name: ngc-secret