apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    openshift.io/display-name: yu-test-nim-deployment-1
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-name: nvidia-runtime-gpu
    opendatahub.io/template-display-name: NVIDIA Inference Microservice
    opendatahub.io/accelerator-name: migrated-gpu
  name: yu-test-nim-deployment-1
  namespace: yu-nim-test-project-1
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  containers:
    - name: kserve-container
      image: 'ghcr.io/huggingface/text-generation-inference:1.4.0'
      command:
        - text-generation-launcher
      args:
        - '--model-id=/mnt/models/'
        - '--port=3000'
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: HUGGINGFACE_HUB_CACHE
          value: /tmp/hf_hub_cache
        - name: TRANSFORMER_CACHE
          value: /tmp/transformers_cache
      readinessProbe:
        exec:
          command:
            - curl
            - 'localhost:3000/health'
        initialDelaySeconds: 30
      livenessProbe:
        exec:
          command:
            - curl
            - 'localhost:3000/health'
        initialDelaySeconds: 30
      ports:
        - containerPort: 3000
          protocol: TCP
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: 2
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: 2
      affinity: {}
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  replicas: 1
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - effect: NoSchedule
      key: odh-notebook
      operator: Exists
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
