apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: 'true'
metadata:
  name: yu-test-nim-deployment-1
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: yu-test-nim-deployment-1
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-name: nvidia-runtime-gpu
    opendatahub.io/template-display-name: NVIDIA Inference Microservice
    opendatahub.io/accelerator-name: migrated-gpu
  namespace: yu-nim-test-project-1
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  supportedModelFormats:
    - name: nvidia-nim-mistral-7b-instruct-v03
  protocolVersions:
    - grpc-v2
  multiModel: false
  containers:
    - env:
        - name: NIM_CACHE_PATH
          value: /mnt/models
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: nvidia-nim-secrets
      name: kserve-container
      image: 'nvcr.io/nim/meta/mistral-7b-instruct-v03:1.0.0'
      ports:
        - containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: 2
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: 2
      affinity: {}
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
  imagePullSecrets:
    - name: ngc-secret
  replicas: 1
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - effect: NoSchedule
      key: odh-notebook
      operator: Exists
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
