apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: 'true'
metadata:
  name: yu-test-nim-deployment-4
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: yu-test-nim-deployment-4
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-name: nvidia-runtime-gpu
    opendatahub.io/template-display-name: NVIDIA Inference Microservice
    opendatahub.io/accelerator-name: migrated-gpu
  namespace: yu-nim-test-project-4
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  supportedModelFormats:
    - name: mixtral-8x22b-instruct-v01
      version: latest
      autoSelect: true
      priority: 1
  protocolVersions:
    - grpc-v2
    - v2
  multiModel: false
  containers:
    - env:
        - name: NIM_CACHE_PATH
          value: /mnt/models
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: nvidia-nim-secrets
      name: kserve-container
      image: 'nvcr.io/nim/meta/mixtral-8x22b-instruct-v01:latest'
      ports:
        - containerPort: 8000
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /mnt/models/cache
          name: nim-pvc
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: 1
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: 1
      affinity: {}
  imagePullSecrets:
    - name: ngc-secret
  volumes:
    - name: nim-pvc
      persistentVolumeClaim:
        claimName: nim-pvc
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
  replicas: 1
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - effect: NoSchedule
      key: odh-notebook
      operator: Exists
